Repository infamousjoeg/cybr-cli, pull requests merged in 2021-03, with the labels that each got.

#83 #70 Add auto completion tab for fish, bash, zsh and powershell
  README.md
  cmd/completion.go
Labels: enhancement

#89 Add concurrent sessions to the CLI #88
  cmd/logon.go
Labels: enhancement

#97 #96 allow more than 2 certificates in cert chain
  pkg/cybr/conjur/conjurrc.go
Labels: bug

#101 Add installation instruction for AWS CloudShell
  README.md
Labels: documentation, enhancement

#94 #90 add no limit to default cybr conjur list command
  cmd/conjur.go
Labels: enhancement

#93 V0.1.2 beta #47 account move
  cmd/accounts.go
  pkg/cybr/api/responses/getaccount.go
Labels: enhancement

#99 Resolves #98 so windows login works correctly
  pkg/cybr/conjur/client.go
  pkg/cybr/conjur/conjurrc.go
  pkg/cybr/conjur/netrc.go
Labels: bug, help wanted

#92 Add --password flag so CCP can retrieve REST API password #66
  cmd/logon.go
Labels: enhancement
