Repository infamousjoeg/cybr-cli, pull requests merged in 2021-01, with the labels that each got.

#20 Expand safes
  cmd/safes.go
  pkg/cybr/api/safes.go
  pkg/cybr/api/safes_test.go
  pkg/cybr/helpers/httpjson/httpjson.go
  pkg/cybr/version.go
  release.json
Labels: enhancement

#19 Expand application api cli
  cmd/applications.go
  pkg/cybr/api/applications.go
  pkg/cybr/api/applications_test.go
Labels: enhancement

#29 Safe members
  cmd/accounts.go
  cmd/applications.go
  cmd/safes.go
  pkg/cybr/api/safes.go
  pkg/cybr/api/safes_test.go
Labels: enhancement

#34 Dev creating application flow
  dev/add-delete-pas-application.sh
Labels: documentation

#40 Add #38 conjur logoff v006
  cmd/conjur.go
Labels: enhancement

#48 Fix #42 RADIUS authentication support for push, append, challenge/response modes
  README.md
  cmd/logoff.go
  cmd/logon.go
  pkg/cybr/api/auth.go
  pkg/cybr/api/client.go
Labels: customer, enhancement

#43 #30 Unsuspend a user from failed logon attempts
  cmd/users.go
  pkg/cybr/api/users.go
  pkg/cybr/api/users_test.go
Labels: enhancement

#53 Fix 52 conjur logon fail
  cmd/conjur.go
  pkg/cybr/conjur/client.go
  pkg/cybr/conjur/conjurrc.go
  pkg/cybr/conjur/logon.go
Labels: bug

#54 Fix #52 conjur logon fail
  cmd/conjur.go
  pkg/cybr/conjur/client.go
  pkg/cybr/conjur/conjurrc.go
Labels: enhancement

#57 #49 add account actions
  cmd/accounts.go
  pkg/cybr/api/accounts.go
  pkg/cybr/api/accounts_test.go
Labels: enhancement

#61 Fix #60 auto docs v.0.1.0
  cmd/root.go
  docs/cybr.md
  docs/cybr_accounts.md
  docs/cybr_accounts_add.md
  docs/cybr_accounts_delete.md
  docs/cybr_accounts_get.md
  docs/cybr_accounts_list.md
  docs/cybr_applications.md
  docs/cybr_applications_add-authn.md
  docs/cybr_applications_add.md
  docs/cybr_applications_delete-authn.md
  docs/cybr_applications_delete.md
  docs/cybr_applications_list-authn.md
  docs/cybr_applications_list.md
  docs/cybr_conjur.md
  docs/cybr_conjur_append-policy.md
  docs/cybr_conjur_enable-authn.md
  docs/cybr_conjur_get-secret.md
  docs/cybr_conjur_info.md
  docs/cybr_conjur_list.md
  docs/cybr_conjur_logoff.md
  docs/cybr_conjur_logon-non-interactive.md
  docs/cybr_conjur_logon.md
  docs/cybr_conjur_replace-policy.md
  docs/cybr_conjur_rotate-api-key.md
  docs/cybr_conjur_set-secret.md
  docs/cybr_conjur_update-policy.md
  docs/cybr_logoff.md
  docs/cybr_logon.md
  docs/cybr_safes.md
  docs/cybr_safes_add-member.md
  docs/cybr_safes_add.md
  docs/cybr_safes_delete.md
  docs/cybr_safes_list-members.md
  docs/cybr_safes_list.md
  docs/cybr_safes_remove-member.md
  docs/cybr_safes_update.md
  docs/cybr_users.md
  docs/cybr_users_unsuspend.md
  docs/cybr_version.md
  docs/main.go
  generate-docs
Labels: enhancement

#55 Fix #31 users cmds v0.1.0
  cmd/users.go
  pkg/cybr/api/users.go
  pkg/cybr/api/users_test.go
Labels: enhancement
